language: node_js
# nodejs版本
node_js:
    - '14.4.0'

install:
- npm install

script:
- npm run build

deploy:
  provider: s3
  access_key_id: $AccesskeyID
  secret_access_key: $SecretAccesskey
  bucket: "carrie-vue-exercises"
  skip_cleanup: true
  region: "us-east-2"
  local_dir: dist

branches:
  only:
    - master