language: node_js
# nodejs版本
node_js:
    - '14.4.0'

install:
- npm install

script:
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GIT_HUB_TOKEN
  local-dir: ./dist # 將要上傳的目錄設定為 build 完之後的目錄

on:
  branch: master